---

- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
  pre_tasks:
    - name: "Wait 20 seconds for target connection to become reachable/usable."
      # Your code here
      command: sleep 20s

    - name: "install python for Ansible."
      become: true
      apt:
        name: [ "python3" ]
        state: latest
        update_cache: yes

  roles:
    # Your code here
    - configure-server
