---
- name: "update packages"
  apt:
    update_cache: yes

#- name: "upgrade packages"
#  apt:
#    upgrade: yes

#- name: "remove dependencies that are no longer required"
#  apt:
#    autoremove: yes

- name: "install dependencies"
  apt:
    name: [ "python3", "npm", "nodejs", "tar", "gzip" ]
    state: latest
    update_cache: yes

- name: "Change npm version to 7.7.5"
  command: npm install -g npm@7.7.5

- name: "install pm2"
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
