---
- name: "Create new dir 'backend'"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Move backend files"
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "Decompress files"
  shell: |
    cd ~/backend
    tar -xzf artifact.tar.gz

- name: "npm install"
  shell: |
    cd ~/backend
    npm install

- name: "Start pm2 server"
  shell: |
    cd ~/backend
    pm2 start npm -- run start
  environment:
    ENVIRONMENT: "{{ lookup('env', 'ENVIRONMENT') }}"
    NODE_ENV: "{{ lookup('env', 'NODE_ENV') }}"
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
