---
- name: "Create new directory 'backend'"
  file:
    path: ~/backend
    state: directory

- name: "Move compressed backend Archive"
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: "Decompress backend Archive"
  unarchive:
    src: ~/backend/artifact.tar.gz
    dest: ~/backend/
    remote_src: yes

- name: "Remove compressed Archive"
  file:
    path: ~/backend/artifact.tar.gz
    state: absent

- name: "Execute 'npm install'"
  command: npm install
  args:
    chdir: ~/backend

- name: "Execute 'npm run build'"
  command: npm run build
  args:
    chdir: ~/backend

- name: "Start pm2 server (with .env)"
#  command: pm2 start npm -- run start
  command: pm2 start -f ./main.js
  args:
    chdir: ~/backend
  environment:
    ENVIRONMENT: "{{ lookup('env', 'ENVIRONMENT') }}"
    NODE_ENV: "{{ lookup('env', 'NODE_ENV') }}"
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
