---
- name: "Create new directory 'backend'"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Move compressed backend Archive"
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "Decompress backend Archive"
  command: tar -xzf artifact.tar.gz
    rm -f artifact.tar.gz

- name: "Remove compressed Archive"
  command: rm -f artifact.tar.gz

- name: "Peform: npm install"
  command: npm install

- name: "Peform: npm build"
  command: npm build

- name: "Start pm2 server"
  command: pm2 start npm -- run start
  environment:
    ENVIRONMENT: "{{ lookup('env', 'ENVIRONMENT') }}"
    NODE_ENV: "{{ lookup('env', 'NODE_ENV') }}"
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
