---
- name: "Create new directory 'backend'"
  file:
    path: ~/backend
    state: directory

- name: "Move compressed backend Archive"
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: "Decompress backend Archive"
  unarchive:
    src: ~/artifact.tar.gz
    dest: ~/
    remote_src: yes

- name: "Remove compressed Archive"
  file:
    path: ~/backend/artifact.tar.gz
    state: absent

- name: "Execute 'npm install'"
  command: npm install
  args:
    chdir: ~/backend

- name: "Execute 'npm run build'"
  command: npm run build
  args:
    chdir: ~/backend

- name: "Start pm2 server"
  command: pm2 start npm -- start
  args:
    chdir: ~/backend
