---
- name: "Move compressed backend Archive"
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: "Decompress backend Archive"
  unarchive:
    src: ~/artifact.tar.gz
    dest: ~/
    remote_src: yes

- name: "Remove compressed Archive"
  file:
    path: ~/artifact.tar.gz
    state: absent

- name: "Execute 'npm install'"
  command: npm install
  args:
    chdir: ~/

- name: "Execute 'npm run build'"
  command: npm run build
  args:
    chdir: ~/

- name: "Start pm2 server (with .env)"
  command: pm2 start npm -- start
  args:
    chdir: ~/
  environment:
    ENVIRONMENT: "{{ lookup('env', 'ENVIRONMENT') }}"
    NODE_ENV: "{{ lookup('env', 'NODE_ENV') }}"
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
